### ISSUE TITLE
Opening dropdown menu should close all other instances of <vaadin-dropdown-menu>

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-select#118]
Depends on #117 

This issue is valid after #117 is resolved (only if we agree to change the behavior).

After making `<vaadin-dropdown-menu-overlay>` modeless, this issue will appear:

![peek 2018-04-19 16-59](https://user-images.githubusercontent.com/6059356/38996059-04fa1bec-43f3-11e8-8ad5-05ee5488d347.gif)

It's a bad UX. Opening the <vaadin-dropdown-menu> should close all other instances of <vaadin-dropdown-menu> 

Most of popular dropdown menus could be an example, e.g. https://www.webcomponents.org/element/PolymerElements/paper-dropdown-menu/demo/demo/index.html

**Comment by tomivirkki** [comment]
Closing as this is not currently an issue
