### ISSUE TITLE
Should provide a way to clear the input

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-select#12]
After selecting an item, you cannot clear the input, you can select another item but not empty.
Probably a `close` button like in combo-box would be nice.

As a workaround, you can add an empty valued item to select it. 

```
          <vaadin-dropdown-menu>
            <template>
              <vaadin-list-box >
                <vaadin-item label="">&nbsp;</vaadin-item>
                <vaadin-item>Jose</vaadin-item>
              </vaadin-list-box>
            </template>
          </vaadin-dropdown-menu>
```

**Comment by jouni** [comment]
This is not standard behavior for a dropdown menu (having a “clear” button by default). The standard way of doing this is providing an ”empty” option/item in the list, like in your workaround.

But it could be a nice additional feature. Needs a bit more though how it would work in different situations, and some user testing.

**Comment by heruan** [comment]
At first I thought it was an element which on click would provide a stateless list of items to click on (similar to `MenuBar` in Framework or [dropdowns](https://getbootstrap.com/docs/4.0/components/dropdowns/) in Bootstrap), where there is no *selection* or *selected elements*, so there's nothing to *clear* or *reset*.

Maybe I'm not understanding the rationale behind this component. How is it supposed to differ from `combo-box`?

**Comment by jouni** [comment]
For the use case you describe, we are going to build `vaadin-menu-button`. We are using the same naming as Paper elements, and naming which is quite established for UI (https://en.wikipedia.org/wiki/Widget_(GUI)).

`vaadin-dropdown-menu` is basically meant as a replacement for the native `select` element, but with more features and better styling support.

The main difference to combo box is that in a dropdown menu you should generally limit the number of items/options to 5–10, whereas in a combo box you can have hundreds (possibly thousands) of items/options to filter and choose from. Visually they look pretty much identical.

**Comment by heruan** [comment]
Thank you for the explanation!

> The main difference to combo box is that in a dropdown menu you should generally limit the number of items/options to 5–10, whereas in a combo box you can have hundreds (possibly thousands) of items/options to filter and choose from. Visually they look pretty much identical.

Is this worth a separate component? Why not a specialization of `combo-box`?

**Comment by jouni** [comment]
We’ve surely thought about that, and it would be nice to have them build up from the same foundation. But at least at this very moment, it’s not the best way for us to implement this new component.

The combo box element has a lot of legacy already built-in, and needs some refactoring in the future, so it’s probably safer to not couple them tightly right now.

Also, allowing keyboard in combo box brings in a lot of complexity on mobile devices (technical and design-wise), which is another reason to keep these separate.

**Comment by yuriy-fix** [comment]
Decided with the team not to be implemented.

**Comment by web-padawan** [comment]
Let's reconsider that in future, if we receive a feedback from the customers regarding `clearButtonVisible` API not available in `vaadin-select`
