### ISSUE TITLE
Improve “type to focus” behavior

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-select#170]
### Description
The user should be able to focus an item by typing some of the first letters of its textual representation (just like with the native `<select>`).

Currently, it is only possible to focus an item by typing the first letter of it, and subsequent letters focus other items.

#### Live Demo
https://vaadin.com/components/vaadin-dropdown-menu/html-examples/dropdown-menu-basic-demos

**Comment by mstahv** [comment]
I can't even make the "first letter typing" work.

**Comment by limonte** [comment]
> I can't even make the "first letter typing" work.

Yeah, it currently works differently from the native input. A user need to open the overlay by pressing Enter or Space odn only then it'll be possible to type the first letter.

**Comment by mstahv** [comment]
Nope, can't make it work :-( 

![screenflick movie 46](https://user-images.githubusercontent.com/1478052/47155320-1cf99180-d2ed-11e8-9e05-65fc4996713b.gif)

**Comment by mstahv** [comment]
Yep, that's it.

In the example the first letter is upper case, so it naturally typed it in upper case. It might be that it is just me, but I'd say it is quite common to start with capitals if the options start with capitals.

**Comment by mstahv** [comment]
And yes, if there is a focus in the field and I start typing some option, I'd expect to be able to select an option right away.

**Comment by johannesh2** [comment]
I would expect that the value can be selected without opening the overlay by just typing when the focus is on the field. Is this ticket about it or should I create another one?

**Comment by jouni** [comment]
They are related but slightly different. I would keep both open.

**Comment by web-padawan** [comment]
Fixed by vaadin/vaadin-list-mixin#50 and released as `vaadin-list-mixin` 2.2.0 🎉
