### ISSUE TITLE
Flow support for vaadin-select?

### ISSUE THREAD

**Issue by RaresI** [vaadin/vaadin-select#172]
Hello,

When can we expect the Java API for vaadin-select? The Dropdown, aka select, is a basic control, it should have been implemented before the Combo.

Thanks,
Rares

**Comment by web-padawan** [comment]
Hello, the tracking issue for this feature is here: vaadin/vaadin-select-flow#1

You can see the status for features planned to land in the next versions of Vaadin platform here:
https://github.com/orgs/vaadin/projects/1

In particular, Java API for this component is planned to be landed in V13.
