### ISSUE TITLE
Cannot bundle with Parcel.

### ISSUE THREAD

**Issue by dwkns** [vaadin/vaadin-select#173]
### Description
[Bower](https://bower.io) is depreciated. It is recommended (by Bower) to use [Webpack](https://webpack.js.org) or [Parcel](https://parceljs.org) with [Yarn](https://yarnpkg.com/lang/en/) instead. 

Bundling fails when using Yarn and Parcel. 
Bundling also fails when using NPM and Parcel. 

#### Steps to Reproduce
```
$ mkdir vaadin-test
$ cd vaadin-test
$ yarn init -y
$ yarn add parcel-bundler --dev
$ yarn add @vaadin/vaadin-select 
```

HTML
```
<!DOCTYPE html>
<html lang='en'>
<head>
  <meta charset='UTF-8'>
  <title>vaadin demo</title>
</head>
<body>
  <vaadin-select>
      <template>
          <vaadin-list-box>
              <vaadin-item>Jose</vaadin-item>
              <vaadin-item>Manolo</vaadin-item>
              <vaadin-item>Pedro</vaadin-item>
          </vaadin-list-box>
      </template>
  </vaadin-select>
  <script src="./index.js"></script>
</body>
</html>
```

JS

```
 import '@vaadin/vaadin-select/vaadin-select.js';`
```
Run the app
```
$ parcel index.html
```

#### Expected Results
Successful compilation.

#### Actual Results
![screenshot 2018-12-13 at 11 43 02](https://user-images.githubusercontent.com/5578117/49936601-49382580-fecc-11e8-931e-163b8d3a9379.png)

### Browsers Affected
n/a

### Versions

- @vaadin/vaadin-select@2.0.0
- node v11.4.0
- parcel-bundle 1.10.3

**Comment by web-padawan** [comment]
Thanks for the issue. It looks like the dependency is used but missing from `package.json`.
Seems quite critical to me.
