### ISSUE TITLE
[bug] Still can't bundle with Parcel.

### ISSUE THREAD

**Issue by dwkns** [vaadin/vaadin-select#176]
### Description
Bundling fails when using Yarn and Parcel.

#### Steps to Reproduce
As per https://github.com/vaadin/vaadin-select/issues/173

#### Expected Results
Successful compilation.

#### Actual Results
![screenshot 2018-12-14 at 18 39 48](https://user-images.githubusercontent.com/5578117/50021069-d1532380-ffcf-11e8-8b11-245e611768b8.png)

### Browsers Affected
n/a

### Versions

@vaadin/vaadin-select@2.0.1
node v11.4.0
parcel-bundle 1.10.3

**Comment by web-padawan** [comment]
Thanks again. Sorry for the inconvenience, we definitely lack of proper checks for this.
Once we switch to ES modules codebase, it would be easier to track with `eslint-plugin-import`

Actually `vaadin-list-box` is kind of "peer dependency" of `vaadin-select` but assuming the fact the style modules are being used it would make sense to bring it as an actual dependency.

https://github.com/vaadin/vaadin-select/blob/150d1f7d97013ad064a14ab950eb061943eb8e8a/theme/lumo/vaadin-select-styles.html#L11

**Comment by dwkns** [comment]
@web-padawan that fixed it. 

This might be useful to you for testing (I use it all the time). It's a bash script which creates the simplest of ES6 projects and launches parcel to bundle and serve the project. You can have clean test environment running in < 30 secs. 

This structure (JS Import, bundle and serve with Parcel) would make a much better 'demo' than the current one which relies on the outdated Bower. I can create a PR if you want me to. 

````bash
#!/usr/bin/env bash

######## Ask for a project name or use default 'demoProject'
if [ -z ${1+x} ]; then # have we passed in a variable $1
    echo "Nothing passed in..."
    echo "You can use '${0##*/} <projectName>' as a shortcut."
    echo
    read -p "Enter project name (default -> demoProject) : " PROJECTNAME
    echo
    PROJECTNAME=${PROJECTNAME:-demoProject}
else 
    
    echo  "Setting project name to '$1'"
    PROJECTNAME=$1
fi

######## Does the folder already exist? Do you want overide it?
if [ -d "$PROJECTNAME" ]; then
  read -p "Project $PROJECTNAME already exists delete it y/n (default - y) : " DELETEIT
  DELETEIT=${DELETEIT:-Y}

  if [  "$DELETEIT" = "Y" ] || [  "$DELETEIT" = "y" ] ; then
   rm -rf $PROJECTNAME
  else
    echo "OK not doing anything & exiting" 
    exit 0
  fi
fi

echo "Project $PROJECTNAME will be created!"

######## Create the folder
mkdir -p $PROJECTNAME
cd "$PROJECTNAME"

######## Init the project with auto-defaults, add Parcel.
yarn init -y
yarn add parcel-bundler --dev
yarn add parcel-plugin-clean-dist --dev


######## Do some processing of package.json to add build scrips & title.

# change the name property of package.json (need to save temp file first)
tmp=$(mktemp) 
JQVAR=".name = \"$PROJECTNAME\""
jq "$JQVAR" package.json > "$tmp" && mv "$tmp" package.json

# add some build scripts to package.json
tmp=$(mktemp) 
JQVAR='.scripts |= .+ { "serve": "parcel src/index.html --open", "build": "parcel build src/index.html" }'
jq "$JQVAR" package.json > "$tmp" && mv "$tmp" package.json


######## Add source folder and files. 
mkdir 'src'

cat >src/index.html <<'EOL'
<!DOCTYPE html>
<html lang='en'>
<head>
  <meta charset='UTF-8'>
  <title>{{page-title}}</title>
</head>
<body>
  <h1>Parcel bootstrap project : {{page-title}}</h1>
  <p>Make it into something cool</p>
  <script src="./index.js"></script>
</body>
</html>
EOL

cat >src/index.js <<'EOL'
import './main.scss';
const paragraph = document.createElement('p');
paragraph.innerText = 'This is a paragraph added from JS which shows bundling is working.';
document.body.appendChild(paragraph); 
EOL

cat >src/main.scss <<'EOL'
$brand: #4A90E2;
$brand-alternate: #F5A623;

body {
    font-family: -apple-system, Sans-Serif;
    color: $brand;
}

h1 {
    font-size: 24pt;
    color: $brand-alternate;
}
EOL

######## Put the project name into the HTML Title. 
sed -i "" -e "s/{{page-title}}/$PROJECTNAME/g" ./src/index.html


######## Start the server.
yarn serve
````

**Comment by web-padawan** [comment]
@dwkns wow, that's cool! Thanks, will try it out and consider running parcel in CI.
