### ISSUE TITLE
Selected item not updated with renderer

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-select#180]
### Description
When using the `renderer` and updating the selected `vaadin-item`'s text content, the text is not updated inside the `vaadin-select-text-field` and it still shows the old text value.

#### Live Demo
Noup

#### Steps to Reproduce
1. Create `vaadin-select`
2. Set a `renderer` to it like in any of the demos and create `vaadin-item`s in it
3. Select an `vaadin-item`
4. Update the textContent for the selected `vaadin-item` (doesn't matter if you call `render()` after)

#### Expected Results
The selected item text content should be updated inside the text field

#### Actual Results
The selected item text content is not updated in the text field, it is only updated in the drop down menu

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### Versions
- vaadin-select: v2.0.2

**Comment by web-padawan** [comment]
Native `<select>` works that way, so from that point of view our component is inconsistent.

The items are expected to be updated by either calling `render()` or replacing `renderer` (the latter will call `render()` automatically and update the item content).

So, it sounds like swapping the `renderer` should update the selected item. 
Any other modifications to item textContent are not supposed to work.

Currently it removes the selected item (and it should update). This should be fixed.
