### ISSUE TITLE
Focused select should also allow selecting an item with the keyboard without opening the overlay

### ISSUE THREAD

**Issue by johannesh2** [vaadin/vaadin-select#184]
Focused select should also allow selecting an item with the keyboard without opening the overlay. I'd expect select to behave like native HTML select.

**Comment by samiheikki** [comment]
@tomivirkki Which behaviour would be correct for this:
1. Native Select: You can type multiple characters for example "M" and "O" and it would select value like "Monaco".
2. Vaadin-list-mixin: For letter "M" it would select "Monaco" but when typing "O" it would select "Ontario": https://github.com/vaadin/vaadin-list-mixin/blob/master/vaadin-list-mixin.html#L148

**Comment by tomivirkki** [comment]
IMO it should work like native select. @jouni wdyt?

**Comment by jouni** [comment]
> IMO it should work like native select. @jouni wdyt?

Yes, like I’ve tried to describe in #170 

> Currently, it is only possible to focus an item by typing the first letter of it, and subsequent letters focus other items.

**Comment by SpaVec** [comment]
I have started working on this issue. : https://github.com/SpaVec/vaadin-select
I have implemented it in a similar way as the native select tag. The slight difference being:
(on chrome and firefox at least) the native select forces you to finish typing the name of the item before you can search again for another one. I just made it so that it resets when you type a non-matching letter because it seems more intuitive and less cumbersome.

I am unsure how to handle the spacebar key though as the tests suggest it should open the overlay.
However, since items can contain spaces, wouldn't it make more sense to include spaces in this functionality ?

**Comment by jouni** [comment]
> I have started working on this issue

Great – much appreciated!

> The slight difference being: (on chrome and firefox at least) the native select forces you to finish typing the name of the item before you can search again for another one. I just made it so that it resets when you type a non-matching letter because it seems more intuitive and less cumbersome.

Yeah, a delay would be the “correct” behavior. But I’m happy to test how your solution feels as an end user.

> I am unsure how to handle the spacebar key though as the tests suggest it should open the overlay.

It’s okay to ignore spaces. At least Safari works like that, that the space key always opens the dropdown.

**Comment by jouni** [comment]
One small improvement suggestion: we should start finding a matching item after the currently selected index (and wrap around at the end), so that you can loop through items like “Option 1, Option2, Option 3” (items with the same starting characters).

**Comment by SpaVec** [comment]
Thanks for the feedback, I have added functionality to cycle through items starting with the same character.
Let me know what you think.

**Comment by jouni** [comment]
It’s close, but not exactly. Here’s how I think it should work:

Given the items `Opt 1`, `Opt 2` and `Opt 2`:

- Focus the field
- Type `op` -> `Opt 1` gets selected
- Type `op` -> `Opt 2` gets selected
- Type `opt` -> `Opt 3` gets selected
- Type `o` -> `Opt 1` gets selected

I hope that makes it clearer.

**Comment by SpaVec** [comment]
Got it! It should now work properly as you described.
