### ISSUE TITLE
Theme Styling 'Small'

### ISSUE THREAD

**Issue by roomtek** [vaadin/vaadin-select#186]
### Description
The small theme feature is missing from vaadin-select. Adding the attribute does not change the style of the element. 

I currently use a custom style to add the desired effect:

`:host([theme~="small"]) [selected] {
		    padding: 0;
   			min-height: var(--lumo-size-s);
		}`

#### Steps to Reproduce
 add theme="small"

#### Expected Results

![image](https://user-images.githubusercontent.com/528961/53931450-306e8480-4063-11e9-84c9-93e12addb17c.png)

#### Actual Results

![image](https://user-images.githubusercontent.com/528961/53931474-4bd98f80-4063-11e9-8804-5c5c32f231b4.png)

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari 9
- [X] Safari 8
- [X] IE 11

### Versions 
- vaadin-select: v2.0.3

**Comment by web-padawan** [comment]
Nice catch. We should cover this with visual test.
