### ISSUE TITLE
Imported web component does not function correctly

### ISSUE THREAD

**Issue by BBKolton** [vaadin/vaadin-select#206]
### Description

Importing and attempting to use the Vaadin Select Polymer 3 web component does not work. The field appears with correct iconography and css formatting, but clicking the box does not open the list to select from. Instead, a very small white circle is appearing over my (black) header bar, which then instantly disappears

#### Reproduction
package.json
```json
{
  "name": "projectname",
  "private": true,
  "version": "0.0.1",
  "description": "Stencil App Starter",
  "scripts": {
    "build": "stencil build",
    "start": "stencil build --dev --watch --serve",
    "test": "stencil test --spec --e2e",
    "test.watch": "stencil test --spec --e2e --watchAll"
  },
  "dependencies": {
    "@stencil/core": "1.0.3",
    "@vaadin/vaadin-select": "^2.1.5"
  },
}
```

app-root.tsx
```typescript
import { Component, h } from "@stencil/core";
import "@vaadin/vaadin-select";

@Component({
  tag: "app-root",
  styleUrl: "app-root.css",
  shadow: true
})
export class AppRoot {
  render() {
    return (
      <div>
        <main>
          <div>
            <vaadin-select>
              <template>
                <vaadin-list-box>
                  <vaadin-item>Jose</vaadin-item>
                  <vaadin-item>Manolo</vaadin-item>
                  <vaadin-item>Pedro</vaadin-item>
                </vaadin-list-box>
              </template>
            </vaadin-select>
          </div>
        </main>
      </div>
    );
  }
}
```

Use [StencilJS](https://stenciljs.com/docs/getting-started) to start a new project, then replace the files with those above. Run the stencil app, and the component should not work.

#### Steps to Reproduce
Click button

#### Expected Results
Select list opens up

#### Actual Results
Tiny white circle appears somewhere briefly, then dissapears

### Browsers Affected

- [ x ] Chrome
- [ x ] Firefox
- [ ? ] Edge
- [ x ] Safari 9
- [ ? ] Safari 8
- [ ? ] IE 11

### Versions

- vaadin-select: v2.1.5
- webcomponents: vX.X.X (not present)

**Comment by BBKolton** [comment]
### Addendum
While testing other components, I ran into the same issue with the context item's example, which uses `vaadin-list-box` just as the select does. Perhaps the issue lies in there?

**Comment by tomivirkki** [comment]
I have a feeling this has to do with the `<template>` syntax which has proven to be problematic when combined with templating engines (other than Polymer). Prefer using the `renderer` API instead, example: https://github.com/vaadin/vaadin-select/blob/master/README.md

**Comment by BBKolton** [comment]
Thanks for the response. I was able to shim the renderer method in and get it working. However, manually changing the render method of the component is far from preferable. Do you have any plans to address the issue at this time?

**Comment by tomivirkki** [comment]
Our `<template>` APIs were originally influenced a lot by Polymer. The implementation is based on Polymer and they primarily work with Polymer apps. Later we introduced the templating engine agnostic `renderer` functions, which should be preferred in most cases nowadays. We haven't yet deprecated `<template>` APIs officially, but are discussing whether we want to support some kind of `<template>` based APIs in the future as we're cutting down our dependencies to Polymer.

**Comment by LordOfTheRams** [comment]
I was also struggling with a dynamic list inside a select. The only way to make it work was indeed with the renderer function. The only problem left was to access the dynamic data from inside the renderer function. The function just has the parameters root and select. You cannot access the properties from the outer LitElement.
```

class RMSTerminView extends connect(store)(LitElement) {
....
static get properties() {
    return {
      senderlist: {
        type: Array,
        hasChanged: () => true
      },
    }
  }

  render() {

    return html`
      <vaadin-select label="Sender" id="sender" .renderer="${this.selectRenderer}"  value="" >
          </vaadin-select>
   `;
   }

   selectRenderer(root, select) {
       let myList =  this.senderlist.map((s) => html`<vaadin-item label="${s.Bezeichnung}">${s.RmsID}</vaadin-item>`);
       render(html`<vaadin-list-box>${myList}</vaadin-list-box>`, root);
  }
}
```
this.senderlist inside the renderer function is undefined. Is there a proper way of handling this issue?

**Comment by LordOfTheRams** [comment]
Well, just in case somebody else has the problem and wants to use vaadin select inside a LitElement with Redux. Here is my solution:

`<vaadin-select label="Sender" id="sender" .renderer="${this.mySpecialRenderer(this.senderlist)}" value="${this.sender}" ></vaadin-select>`

Renderer function is pretty much copy & paste from docs. The trick to access the dynamic data (slist in my example), is, to return a closure:

  ```
mySpecialRenderer(slist) {

    return function(root) {
        // Check if there is a list-box generated with the previous renderer call to update its content instead of recreation
        if (root.firstChild) {
          return;
        }
        // create the <vaadin-list-box>
        const listBox = window.document.createElement('vaadin-list-box');
        // append  <vaadin-item> elements
        slist.forEach(function(s) {
          const item = window.document.createElement('vaadin-item');
          item.textContent = s.Bezeichnung;
          item.setAttribute('value', s.RmsID);
          listBox.appendChild(item);
        });
        // update the content
        root.appendChild(listBox);
    }
  }
```
That's pretty much plain javascript and not LitHtml. But that's the only way I got it working. Let me know if there is a smarter way to do it.

**Comment by BBKolton** [comment]
>  We haven't yet deprecated `<template>` APIs officially, but are discussing whether we want to support some kind of `<template>` based APIs in the future as we're cutting down our dependencies to Polymer.

👍 that would be nice to see. You have probably the most fully-featured set of web components out there, which puts you in the unique and cool place to take advantage of the lack of market competition for components. Making sure that when compiled they work with vanilla JS and other web component frameworks would be huge 

Thanks for the reply!

**Comment by web-padawan** [comment]
We will investigate what could be a better API for using with lit-html in the next generation.

The original question has been answered so I think this can be closed.
