### ISSUE TITLE
Not selecting a value clears validator error

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/vaadin-select#265]
### Description
Vaadin version 14.5.3

If you have set a Select set as required through Binder and with setEmptySelectionAllowed(false), you can clear the red validation status by opening the select popup and choosing nothing. 

#### Steps to Reproduce

Code example:
```java
public class MasterDetailView extends VerticalLayout {

    public MasterDetailView() {
        Select<String> select = new Select<>();
        select.setItems("Foo", "Bar");
        select.setEmptySelectionAllowed(false);

        Binder<DummyItem> binder = new Binder<>(DummyItem.class);
        binder.readBean(new DummyItem());
        binder.forField(select).asRequired().bind(DummyItem::getName, DummyItem::setName);

        Button validateB = new Button("Validate", e -> {
            binder.validate();
        });
        add(select, validateB);
    }

    static class DummyItem {
        public String getName() {
            return name;
        }
        public void setName(String name) {
            this.name = name;
        }
        private String name;
    }
}
```
Steps
1. Click validate (makes the Select invalid)
2. Click to open the Select overlay
3. Click outside the overlay to choose nothing -> Select becomes valid again even though there is no value selected

#### Expected Results
Closing the overlay should not change the Select to become valid

#### Actual Results
Closing the overlay makes the Select valid

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge
- [x] iOS Safari
- [x] Android Chrome

### Version
vaadin 14.5.3

**Comment by vlukashov** [comment]
Here is a sample project to reproduce the issue: [select-required-issue-v14.5.3.zip](https://github.com/vaadin/vaadin-select/files/6425611/select-required-issue-v14.5.3.zip)
![select-required-issue](https://user-images.githubusercontent.com/22416150/117110159-636d4980-ad8e-11eb-863e-017fa9aeeec7.gif)
